export let marketCards = [
  {
    imageURL: "/images/market/image (7).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (8).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 2,
  },
  {
    imageURL: "/images/market/image (9).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 0,
  },
  {
    imageURL: "/images/market/image (10).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (7).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (8).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (9).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (10).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
];

export let marketCards2 = [
  {
    imageURL: "/images/market/image (11).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (12).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (13).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (14).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (11).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (12).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (13).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
  {
    imageURL: "/images/market/image (14).png",
    followers: "#2341",
    avatar: "/images/market/Mark.svg",
    userName: "Claynosaurz",
    nameFollow: "@claynosaurz",
    val: 225.31,
    state: 1,
  },
];
